import {User} from "../../types/pages/userInfo/IUser.ts";

export const users: User[] = [{
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Hubbard",
    firstName: "Eula",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
    fullName: "Hubbard Eula",
    address: 'Lviv, Ukraine',
    title: 'profileInformation',
    briefJobDescription: '',
    compensationType: 'fixed rate',
    methodOfPayment: 'Payoneer',
    compensationSchedule: 'weekly',
    fullNameOfSupervisor: 'new',
    lastPaymentDate: '07/09/2023',
    posts: [
        {
            id: 1,
            title: 'Accounting/Bookkeeping',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 2,
            title: 'Digital Forensics',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 3,
            title: 'Legal Internship',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 4,
            title: 'Attorney',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 5,
            title: 'Client Care/Intake Specialist',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 6,
            title: 'Translator/Interpreters',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 7,
            title: 'Social Media Manager',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 8,
            title: 'Marketing Internship',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        },
        {
            id: 9,
            title: 'Paralegal',
            content: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'
        }
    ]
},
    {
        id: 2,
        img: "",
        lastName: "Manning",
        firstName: "Stella",
        email: "comhuhmit@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Manning Stella",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
        posts: []
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Greer",
        firstName: "Mary",
        email: "ujudokon@hottmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Mary Greer",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
        posts: []
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Williamson",
        firstName: "Mildred",
        email: "tinhavabe@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Mildred Williamson",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
        posts: []
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Gross",
        firstName: "Jose",
        email: "gobtagbes@yahoo.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: "Jose Gross",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 6,
        img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Sharp",
        firstName: "Jeremy",
        email: "vulca.eder@mail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Jeremy Sharp",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Lowe",
        firstName: "Christina",
        email: "reso.bilic@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: "Christina Lowe",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 8,
        img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Dean",
        firstName: "Garrett",
        email: "codaic@mail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Garret Dean",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 9,
        img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Parsons",
        firstName: "Leah",
        email: "uzozor@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: 'Leah Parsons',
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 10,
        img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Reid",
        firstName: "Elnora",
        email: "tuhkabapu@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Elnora Reid",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 11,
        img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Dunn",
        firstName: "Gertrude",
        email: "gibo@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
        fullName: "Gertrude Dunn",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 12,
        img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Williams",
        firstName: "Mark",
        email: "tic.harvey@hotmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: "Mark Williams",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 13,
        img: "https://images.pexels.com/photos/761977/pexels-photo-761977.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Cruz",
        firstName: "Charlotte",
        email: "ceuc@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: "Charlotte Cruz",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 14,
        img: "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Harper",
        firstName: "Sara",
        email: "bafuv@hotmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: "Sara Harper",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
    {
        id: 15,
        img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        lastName: "Griffin",
        firstName: "Eric",
        email: "ubi@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: false,
        fullName: "Eric Griffin",
        address: 'Lviv, Ukraine',
        title: 'profileInformation',
        briefJobDescription: '',
        compensationType: 'fixed rate',
        methodOfPayment: 'Payoneer',
        compensationSchedule: 'weekly',
        fullNameOfSupervisor: 'new',
        lastPaymentDate: '07/09/2023',
    },
]